[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/welcome.html"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/home.html"
    [headers.values]
    Access-Control-Allow-Origin = "*"
